sonar.projectKey=Abdu11ahEjaz_cohort-9-mern-15364-abdullah
sonar.organization=abdu11ahejaz

sonar.projectName=FocusNote - Notes App
sonar.projectVersion=1.0

# Analyze both backend and frontend source code
sonar.sources=backend/src,frontend/src

# Exclude test files, build output, and dependencies from the main source scan
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/*.test.jsx,**/coverage/**

# Point to test files separately
sonar.tests=backend/test,frontend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

sonar.sourceEncoding=UTF-8